#define VERSION_MAJOR 2
#define VERSION_MINOR 99
#define VERSION_PATCH 99
#define VERSION_BUILD 99

#define FIX_VERSION_MAJOR VERSION_MAJOR
#define FIX_VERSION_MINOR VERSION_MINOR
#define FIX_VERSION_PATCH VERSION_PATCH
#define FIX_VERSION_BUILD VERSION_BUILD

#define ONEKEY_VERSION_MAJOR 4
#define ONEKEY_VERSION_MINOR 21
#define ONEKEY_VERSION_PATCH 0
#define ONEKEY_VERSION_BUILD 0

// Minimum SE version required for firmware upgrade
#define SE_MINIMUM_VERSION_MAJOR 1
#define SE_MINIMUM_VERSION_MINOR 3
#define SE_MINIMUM_VERSION_PATCH 0
#define SE_MINIMUM_VERSION_UINT32                               \
  (SE_MINIMUM_VERSION_MAJOR | (SE_MINIMUM_VERSION_MINOR << 8) | \
   (SE_MINIMUM_VERSION_PATCH << 16) | (0 << 24))

#define _STR(X) #X
#define VERSTR(X) _STR(X)

#define ONEKEY_VERSION         \
  VERSTR(ONEKEY_VERSION_MAJOR) \
  "." VERSTR(ONEKEY_VERSION_MINOR) "." VERSTR(ONEKEY_VERSION_PATCH)
